services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: docker-compose.env
    ports:
      - "15000:5000"
    depends_on:
      - db
    networks:
      - net

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net

  migrations:
    build: migrations
    command: -connectRetries=20 migrate
    environment:
      FLYWAY_USER: 'postgres'
      FLYWAY_MIXED: 'true'
      FLYWAY_PASSWORD: 'postgres'
      FLYWAY_URL: 'jdbc:postgresql://db:5432/postgres'
    depends_on:
      - db
    networks:
      - net

      
networks:
  net:
    driver: bridge

volumes:
  postgres_data:
