import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme";
import { Typography, Container, Toolbar, AppBar } from "@mui/material";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Employee Manager",
  description: "Generated by create next app",
};

const AppBarLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <>
      <AppBar position="fixed">
        <Container maxWidth="xl">
          <Toolbar disableGutters>
            <Typography
              variant="h6"
              noWrap
              component="a"
              href="/"
              sx={{
                mr: 2,
                display: { xs: "flex" },
                fontWeight: 700,
                letterSpacing: ".3rem",
                color: "inherit",
                textDecoration: "none",
              }}
            >
              Employee Manager
            </Typography>
          </Toolbar>
        </Container>
      </AppBar>
      <Container maxWidth="xl" sx={{mt: 10}}>{children}</Container>
    </>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <body className={inter.className}>
            <AppBarLayout>{children}</AppBarLayout>
          </body>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
